### PR TITLE
layer.conf: Define LAYERSERIES_COMPAT to avoid build warnings

### PR DESCRIPTION
**Pull request by agherzan**
Signed-off-by: Andrei Gherzan <andrei@balena.io>

### CODE REVIEW

**Comment by agherzan** [comment]
Friendly ping on this PR.

**Comment by agherzan** [comment]
Hey guys. Any sign of life around?

**Comment by jochenjagers** [comment]
@imyller It would be great if this pull-request could be accepted.

**Comment by agherzan** [comment]
@imyller please merge this PR.

**Comment by agherzan** [comment]
I think this is obvious that we have no chance of getting any support here. I'll close this and maintain a fork while we are using this old node.

**Pull request closed without merging**
