### PR TITLE
Improve build time to use ninja for nodejs recipes

### PR DESCRIPTION
**Pull request by gsikorski**
Tested on the system with `ninja-native` package provided by [meta-browser](https://github.com/OSSystems/meta-browser).

### CODE REVIEW

**Comment by imyller** [comment]
Thank you for your effort @gsikorski 

This is a welcome addition but introduces additional dependency, which may be unwanted for many.

I've looked into recipe of ninja-native and it is actually quite minimal. In meta-browser layer it is also lagging two minor versions behind the more recent ninja build system releases.

Given the simplicity of ninja build system recipe, how would you feel if meta-nodejs layer would carry its own more up-to-date recipe for ninja-native? It's inclusion would be justifiable as node.js build-time dependency.

Also, I strongly feel that ninja build system does not belong to meta-browser (nor meta-nodejs for that matter). It belongs to OpenEmbedded core layers just like make, autotools etc. If those projects decide to include it later, I'd most certainly would deprecate/remove it from meta-nodejs at that time.

**Comment by gsikorski** [comment]
It looks to me that ninja-native recipe belongs to meta-browser and some other small meta repositories that use it (http://layers.openembedded.org/layerindex/branch/master/recipes/?q=ninja). I think it justifies adding it to meta-nodejs as well. The only potential problem I could see with this solution is there would be some systems that use e. g. both meta-nodejs and meta-browser, hence having two ninja recipes available. I think bitbake will be happy, but may sometimes use version of ninja incompatible (not tested) with specific project. Let say we include ninja-native_1.6.0 and meta-browser includes ninja-native_1.4.0 to build chromium browser. Since dependencies in chromium recipe are not tied to particular version of ninja-native, bitbake will use v1.6.0 to build chromium. Since this configuration is not tested, it may fail or produce invalid build. But taking into account the size of this tool, it is probably low risk and minor issue.

**Comment by gsikorski** [comment]
I have just tested build 4.2.2 and there is a problem with this solution. [This](https://github.com/nodejs/node/commit/de224d6e6c9381e71ffee965dbda928802cc438e)  commit removed ninja switch from v4+ :( The only supported way to compile is using make, but it does not pass over multi job switch (-jN).

**Comment by imyller** [comment]
Sad to see the Ninja go :( 
We'll get back to this if it ever returns to Node.js project.
Thank you again for the effort though.

**Pull request closed without merging**
