### PR TITLE
Tooling

### PR DESCRIPTION
**Pull request by bachp**

### CODE REVIEW

**Comment by imyller** [comment]
Lot of changes, new recipes, changes to old code etc.

Could you please provide some information about the content of this PR and rationale behind it.

Thank you.

**Comment by bachp** [comment]
You are right, it was a bit to much for one pull request.

I spli it up into multiples, grouped by topic.

This one should help people using some tools in the NodeJS context, specifically grunt and gulp.
It provides some classes and recipes that help with that. See the commit messages for more details.

The new class added here is required to install npm packages "globall" using `npm -g` these can then be packaged using bitbake.

Let me know if there are any further questions.

**Comment by imyller** [comment]
Thanks. Looking forward for invididual PRs :)

**Comment by bachp** [comment]
The tooling PR now only includes the changes regarding gulp and grunt build tools.

**Pull request merged**
