### PR TITLE
npm-base: Add support for https proxy

### PR DESCRIPTION
**Pull request by raymanfx**
npm was not picking up the environment variable, so we need to pass the flag before calling it.

### CODE REVIEW

**Comment by bachp** [comment]
Could you also implement it for http_proxy

**Comment by imyller** [comment]
Good point @bachp 

Also the native variant should be patched similarly.

Could be done in the context of this PR or separately.

**Comment by bachp** [comment]
btw we already set some env variables via `export`. So for consistency reason we should set them all either via `export` or during the call.

**Comment by imyller** [comment]
I'd prefer the export method. There is slight difference in export and setting in call:

I'd assume export to stay set even if npm opens new (sub-)shell process while in-call might be limited to npm process itself but might not always propagate to it's sub-shells.

**Comment by raymanfx** [comment]
Updated:
- http/https support
- export variables
- support native targets as well, not only cross-compiling ones

**Comment by bachp** [comment]
:+1:

**Comment by imyller** [comment]
LGTM

**Pull request merged**
