### PR TITLE
Don't set npm specific proxy variables in npm.bbclass

### PR DESCRIPTION
**Pull request by bachp**
npm is using the default http*_proxy variables.

### CODE REVIEW

**Comment by imyller** [comment]
This PR is reverting previous attempts to get npm obey Bitbake proxy settings.
This is preferable for some people in restricted build environments, where Bitbake is configured to use proxy for fetching with HTTP_PROXY environment variable.

Care to explain what is the benefit of decoupling the npm and bitbake proxies and completely reverting this feature?

**Comment by imyller** [comment]
If I'm right the rationale behind this is that npm obeys HTTP_PROXY and HTTPS_PROXY environment variables as is. I'm not sure that applies to all previous versions of npm provided by older Node.js versions?

What is the harm of defining NPM_CONFIG_\* versions just to be sure?

**Comment by bachp** [comment]
The issue I ran into was that if the NPM_CONFIG_\* versions were set the proxy was not working at all, removing it made it working. This was with version 4.2.2.

The rational was that npm obeys HTTP_PROXY and HTTPS_PROXY environment variables as is so it seemed unnecessary. But I only tested it with NPM 4.2.2.

**Comment by imyller** [comment]
Just checked. As far as I can see old versions of NPM support HTTP_PROXY and HTTPS_PROXY

If you can resolve the conflicts with the latest version, I'll merge this ASAP.

Thank you.

**Comment by bachp** [comment]
Merge conflicts resolved.

**Pull request merged**
