### PR TITLE
node v8.x.x & support npm 5

### PR DESCRIPTION
**Pull request by ovaar**

### CODE REVIEW

**Comment by pcarranzav** [comment]
@imyller, we'd love to see this merged so we can start using node 8 - do you think it can make it into master soon? thanks! :)

**Comment by ovaar** [comment]
Can we merge this ?

**Comment by bachp** [comment]
@ninox92 could you clean up the commit history a bit. It's not entirely clear to me which commit does what and there are multiple with almost similar commit messages. Also please get rid of the backmerge commit.

Content wise it looks good.

**Comment by ovaar** [comment]
@bachp I created a new pull request and cleaned up the commits

**Pull request closed without merging**
