### PR TITLE
npm-install: do_npm_*(): cd to ${B}

### PR DESCRIPTION
**Pull request by geomatsi**
Change working directory to ${B} prior to running tasks from npm-install
class. This change is needed due to bitbake commit
67a7b8b021badc17d8fdf447c250e79d291e75f7.

Without this change do_npm_* functions are executed with ${TOPDIR}
as a rootdir. As a result they fail to find package.json.

Signed-off-by: Sergey Matyukevich <geomatsi@gmail.com>

### CODE REVIEW

**Comment by imyller** [comment]
Looks good.

**Comment by geomatsi** [comment]
Related bitbake change has been introduced after krogoth release. So this fix is relevant for morty and upstream only.

**Comment by geomatsi** [comment]
BTW npm-install-global seems to be working fine w/o this fix. At least I didn't observed any issues building node-red using morty branches.

**Comment by imyller** [comment]
Are you sure package.json is always in ${B} and not in ${S}?

**Comment by geomatsi** [comment]
IIUC this is the case for npm-install class: B is assigned to ${S} on top of npm-install.bblcass file.

**Comment by geomatsi** [comment]
PR update: v1 -> v2

Make change more future-proof: replace ${B} by ${S} since package.json normally belongs to source directory rather than to build directory.

**Pull request merged**
