### PR TITLE
O.S. Systems pending fixes

### PR DESCRIPTION
**Pull request by otavio**

### CODE REVIEW

**Comment by posborne** [comment]
Just as a general note, I think this layer should probably create branches for the various version of Yocto so we can do limited support of older versions a bit more easily.  This change makes sense on krogroth but would be breaking for other versions.  Initially, it might be fine to have a master, krogoth, and jethro branches.

**Comment by imyller** [comment]
@posborne I agree

**Comment by imyller** [comment]
@otavio `npm` class in new Yocto 2.1 does not match `npm` class in `meta-nodejs` they provide different functionality. Our `npm-install` class matches in purpose.

We have not yet decided what is the proper action to resolve this conflict as Yocto 2.1 `npm` class lacks lot of features and differs in purpose. 

Also moving grunt, bower and gulp from global install to package local install is not proper way to fix this. Yocto 2.1 `npm` class does not support global installs and this PR changes that fundamentally.

ref #39

**Comment by otavio** [comment]
Ok; this is fine.

We had a similar problem to support CHICKEN Scheme[1]. At O.S. Systems we ended writing an overlay for the chicken-install tool (the equivalent of npm) to parse the source and generate the recipe automatically[2]. 
1. http://code.ossystems.com.br/gitweb?p=meta-chicken.git;a=summary
2. http://code.ossystems.com.br/gitweb?p=meta-chicken.git;a=blob;f=scripts/gen-egg-recipes

To be honest, I think a similar approach for nodejs would be very helpful as it alleviates the maintainer hassle and allow for easy upgrade of modules whenever those are release, while allows for stable releases and reproducibility for products.

It is a shame that you guys did not take a more active role at OpenEmbedded-Core mailing list when the npm class patch was submitted, this would have made all this transition way easier. Now I think it will take some more time and energy.

**Comment by imyller** [comment]
Closing this PR.

For more information: `krogoth` branch and comments in #39

**Pull request closed without merging**
