### PR TITLE
Node.js:  Add NativeSDK support

### PR DESCRIPTION
**Pull request by mdavis777**
Adds nativesdk support to nodejs 0.x 4.x and 6.x.

Signed-off-by: Michael Davis michael.davis@essvote.com

### CODE REVIEW

**Comment by imyller** [comment]
Thank you.

I'll test this and merge if it works.

**Comment by imyller** [comment]
I'd like to see PR in each `.inc` file incremented for this change:

For example
`PR = "${INC_PR}.6"` -> `PR = "${INC_PR}.7"`

**Comment by imyller** [comment]
Tested and builds ok. I'll merge if you'd kindly add the `PR` increments.

**Comment by mdavis777** [comment]
Done

**Comment by imyller** [comment]
Excellent. Thank you.

**Comment by imyller** [comment]
@mdavis777 
Thank you for pushing forward with nativesdk build features. 

I personally have no use case for them and they were left ignored both in Node.js core recipes and in npm helper classes; but no more - thanks to you 👍

**Pull request merged**
