### PR TITLE
classes/npm: allow `NPM_ARCH=foo oe_runnpm` to work

### PR DESCRIPTION
**Pull request by codyps**

### CODE REVIEW

**Comment by codyps** [comment]
Not sure if `: ${FOO:=bar}` is a bash-ism. If it is, there is probably an alternate way to achieve the same thing.

**Comment by codyps** [comment]
Just noticed that this doesn't handle the CXX usage, which I'd also need to adjust.

**Comment by imyller** [comment]
Yes missed that one. 

I'm thinking about `npm-native.bbclass` with its own `NPM_NATIVE_ARCH`, `NPM_NATIVE_CXX` and `oe_runnpm_native`. Maybe that would be the most correct and "OE" way of doing this while avoiding bashism etc.

Baking native and target versions to same bbclass ( just like in #7 ) is always possibility but it does not feel as elegant to me.

**Comment by imyller** [comment]
... and I might be wrong and solution in PR #7 is actually the right one (with some improvements) ;)

This is tricky.

**Comment by imyller** [comment]
@jmesmon feedback appreciated :)

There can be common function for some inits just like in #7 but I wanted to keep things clear and simple and separate cleanly target and native functions and their variables. Here flags, ld, arch, cache dir, npm binary are configurable for target and native independently.

Also, this does not break compatibility with earlier versions in any way.

```
DEPENDS += " virtual/node-native"

RDEPENDS_${PN} += " node"

PACKAGE_DEBUG_SPLIT_STYLE = "debug-file-directory"

CCACHE = ""

NPM ?= "npm"
NPM_CACHE_DIR = "${WORKDIR}/npm_cache"
NPM_ARCH ?= "${TARGET_ARCH}"
NPM_LD ?= "${CXX}"
NPM_FLAGS ?= ""

# Target npm

oe_runnpm() {

    export NPM_CONFIG_CACHE="${NPM_CACHE_DIR}"

    [ -n "${http_proxy}" ] && export NPM_CONFIG_PROXY="${http_proxy}"
    [ -n "${https_proxy}" ] && export NPM_CONFIG_HTTPS_PROXY="${https_proxy}"
    [ -n "${HTTP_PROXY}" ] && export NPM_CONFIG_PROXY="${HTTP_PROXY}"
    [ -n "${HTTPS_PROXY}" ] && export NPM_CONFIG_HTTPS_PROXY="${HTTPS_PROXY}"

    bbnote NPM target architecture: ${NPM_ARCH}
    bbnote NPM cache directory: ${NPM_CONFIG_CACHE}
    bbnote NPM HTTP proxy: ${NPM_CONFIG_PROXY}
    bbnote NPM HTTPS proxy: ${NPM_CONFIG_HTTPS_PROXY}

    bbnote ${NPM} --arch=${NPM_ARCH} --target_arch=${NPM_ARCH} ${NPM_FLAGS} "$@"

    LD="${NPM_LD}" ${NPM} --arch=${NPM_ARCH} --target_arch=${NPM_ARCH} ${NPM_FLAGS} "$@" || die "oe_runnpm failed"

}

# Native npm

NPM_NATIVE ?= "npm"
NPM_CACHE_DIR_NATIVE = "${WORKDIR}/npm_cache"
NPM_ARCH_NATIVE ?= "${BUILD_ARCH}"
NPM_LD_NATIVE ?= "${BUILD_CXX}"
NPM_FLAGS_NATIVE ?= ""

oe_runnpm_native() {

    export NPM_CONFIG_CACHE="${NPM_CACHE_DIR_NATIVE}"

    [ -n "${http_proxy}" ] && export NPM_CONFIG_PROXY="${http_proxy}"
    [ -n "${https_proxy}" ] && export NPM_CONFIG_HTTPS_PROXY="${https_proxy}"
    [ -n "${HTTP_PROXY}" ] && export NPM_CONFIG_PROXY="${HTTP_PROXY}"
    [ -n "${HTTPS_PROXY}" ] && export NPM_CONFIG_HTTPS_PROXY="${HTTPS_PROXY}"

    bbnote NPM native architecture: ${NPM_ARCH_NATIVE}
    bbnote NPM cache directory: ${NPM_CONFIG_CACHE}
    bbnote NPM HTTP proxy: ${NPM_CONFIG_PROXY}
    bbnote NPM HTTPS proxy: ${NPM_CONFIG_HTTPS_PROXY}

    bbnote ${NPM_NATIVE} --arch=${NPM_ARCH_NATIVE} --target_arch=${NPM_ARCH_NATIVE} ${NPM_FLAGS_NATIVE} "$@"

    LD="${NPM_LD_NATIVE}" ${NPM_NATIVE} --arch=${NPM_ARCH_NATIVE} --target_arch=${NPM_ARCH_NATIVE} ${NPM_FLAGS_NATIVE} "$@" || die "oe_runnpm_native failed"

}
```

**Comment by codyps** [comment]
Looks OK to me (of course, so did the other ones until I stared at them for a bit longer :)

**Comment by imyller** [comment]
Ok. I'm going to commit that one and close this PR.

I personally do not have a a real-world scenario for using the _native variant so, please open a new PR or plain issue if you feel this needs further improvement :)

Thanks again for your valuable contribution.

**Pull request closed without merging**
